name: cuvs_cagra
constraints:
  build: cuvs_bench.config.algos.constraints.cuvs_cagra_build
  search: cuvs_bench.config.algos.constraints.cuvs_cagra_search
groups:
  base:
    build:
      graph_degree: [16, 32, 48, 64, 96, 128]
      intermediate_graph_degree: [16, 32, 48, 64, 96, 128]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [16, 32, 48, 64, 128, 256, 512]
      search_width: [1, 2, 4, 8, 16, 32, 64]
  mig_1c_4g_20gb:
    build:
      graph_degree: [16, 32, 48, 64, 96, 128]
      intermediate_graph_degree: [16, 32, 48, 64, 96, 128]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [16, 32, 48, 64, 128, 256, 512]
      search_width: [1, 2, 4, 8, 16, 32, 64]
  mig_2c_3g_20gb:
    build:
      graph_degree: [16, 32, 48, 64, 96, 128]
      intermediate_graph_degree: [16, 32, 48, 64, 96, 128]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [16, 32, 48, 64, 128, 256, 512]
      search_width: [1, 2, 4, 8, 16, 32, 64]
  mig_3g_20gb:
    build:
      graph_degree: [16, 32, 48, 64, 96, 128]
      intermediate_graph_degree: [16, 32, 48, 64, 96, 128]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [16, 32, 48, 64, 128, 256, 512]
      search_width: [1, 2, 4, 8, 16, 32, 64]
  mig_4g_20gb_patch1:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [48]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [48]
      search_width: [2]
  mig_4g_20gb:
    build:
      graph_degree: [16, 32, 48, 64, 96, 128]
      intermediate_graph_degree: [16, 32, 48, 64, 96, 128]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [16, 32, 48, 64, 128, 256, 512]
      search_width: [1, 2, 4, 8, 16, 32, 64]
  mig_1c_7g_40gb:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [48]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [48]
      search_width: [2]
  mig_2c_7g_40gb:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [48]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [48]
      search_width: [2]
  mig_3c_7g_40gb:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [48]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [48]
      search_width: [2]
  mig_4c_7g_40gb:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [48]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [48]
      search_width: [2]
  graph_analysis_v2:
    build:
      graph_degree: [16, 32, 48, 64, 96, 128]
      intermediate_graph_degree: [16, 32, 48, 64, 96, 128]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [16, 32, 48, 64, 128, 256, 512]
      search_width: [1, 2, 4, 8, 16, 32, 64]
  profile1:
    build:
      graph_degree: [128]
      intermediate_graph_degree: [128]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [32, 64, 128, 256, 512]
      search_width: [1, 2, 4, 8, 16, 32, 64]
  ncu_recall95_v1_glove_100_inner_k10_bs10000:
    build:
      graph_degree: [64]
      intermediate_graph_degree: [64]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [256]
      search_width: [1]
  ncu_recall95_v1_sift_128_euclidean_k10_bs10000:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [48]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [48]
      search_width: [2]
  knob_thread_block_recall95_v1_sift_128_euclidean_k10_bs10000:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [32]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [64]
      search_width: [4]
      # `thread_block_size` must be 0, 64, 128, 256 or 512
      thread_block_size: [0, 64, 128, 256, 512]
  ncu_recall95_v1_gist_960_euclidean_k10_bs1000:
    build:
      graph_degree: [64]
      intermediate_graph_degree: [64]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [128]
      search_width: [16]
