name: ganns_hnsw
constraints:
  build: cuvs_bench.config.algos.constraints.ganns_build
  search: cuvs_bench.config.algos.constraints.ganns_search
groups:
  base:
    build:
      hierarchical: [True]
      num_of_candidates_build: [16, 32, 64, 128, 256]
      num_of_initial_neighbors: [64]
    search:
      num_of_candidates_search: [16, 32, 64, 128, 256, 512, 1024]
  graph_analysis_v2:
    build:
      hierarchical: [True]
      num_of_candidates_build: [16, 32, 64, 128, 256]
      num_of_initial_neighbors: [64]
    search:
      num_of_candidates_search: [16, 32, 64, 128, 256, 512, 1024]
